### ISSUE TITLE
Automated Project Registration

### ISSUE THREAD

**Issue by Zemerik** [Zemerik/ZemShowcase#10]
Currently, adding your project to the showcase is too much work and makes it hard for users to contribute. To fix this, we need to create a registration form which can collect the required information from an user, and then had his / her project to the showcase with all the details.

**Comment by Bashamega** [comment]
Hello:)

I would like to work on this issue. I will integrate docker, and add the form ui.

**Comment by Zemerik** [comment]
Thanks Adam, assigned to you 👍

**Comment by Bashamega** [comment]
I have tried reading the code, but it is not easy to understand.

**Comment by Zemerik** [comment]
Hey @Bashamega , 

I am not quite sure what you are asking, and don't really seem to remember since I wrote this code a while ago. I suggest that you use the same UI as the `Contact Form` UI, but change the email configuration. 

Regards, 
Zemerik

**Comment by Bashamega** [comment]
> Hey @Bashamega , 
> 
> I am not quite sure what you are asking, and don't really seem to remember since I wrote this code a while ago. I suggest that you use the same UI as the `Contact Form` UI, but change the email configuration. 
> 
> Regards, 
> Zemerik

I mean how do you get the article json?

**Comment by Zemerik** [comment]
I don't remember using an article json during the process, I used emailJS to transfer the information to my email using their public `Service ID`, `TemplateID`, and `Public Access Code`.

**Comment by Bashamega** [comment]
> I don't remember using an article json during the process, I used emailJS to transfer the information to my email using their public `Service ID`, `TemplateID`, and `Public Access Code`. 

I mean, how did you build the article page. Where you are directed to when you click view project.
The article post

**Comment by Zemerik** [comment]
You are redirected to the following path, in which information about the project is added 👇

`src/pages/project/[id].tsx`. 

btw, thanks for fixing the `client side error`

**Comment by Bashamega** [comment]
> You are redirected to the following path, in which information about the project is added 👇
> 
> `src/pages/project/[id].tsx`. 
> 
> btw, thanks for fixing the `client side error`

I am very happy that it got fixed.

I need to know how you get the information of this page

**Comment by Bashamega** [comment]
I am very glad that it worked
