### ISSUE TITLE
[Bug]: Welcoming message github actions

### ISSUE THREAD

**Issue by Bashamega** [Zemerik/ZemShowcase#12]
### What happened?

The GitHub actions are not working.

I would like to rewrite the github actions and fix it

### Add screenshots

![image](https://github.com/user-attachments/assets/d4688901-6782-4007-a961-148b37b3d238)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zemerik** [comment]
Hey Adam, 

You can rewrite the workflow / (s) to fix it. Assigned to you 👍

Regards, 
Zemerik
