### ISSUE TITLE
[Bug]: CSS icon is not visisble

### ISSUE THREAD

**Issue by Bashamega** [Zemerik/ZemShowcase#15]
### What happened?

The CSS logo is not visible on the home page.

### Add screenshots

![image](https://github.com/user-attachments/assets/83412537-cb56-4830-953b-c0968906bb81)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zemerik** [comment]
Thanks for opening the issue,  and informing us about it. The CSS Icon has now been added👍. 

Commit - https://github.com/Zemerik/ZemShowcase/commit/5791cfa62f73eed4a41aa2e592440a32e835eee4

Regards, 
Zemerik
